### PR TITLE
Fix issue 99

### LINKED ISSUE #99: Refactor `Air_sub`, move all `Air_` functions
In STEMMUS_SCOPE.m, all `Air_` functions are called using the script `Air_sub`:

https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/d2fe0a671ab26430f086e1c8ee8272f4db6fa060/src/STEMMUS_SCOPE.m#L747

However, for model maintainability we want to remove all use of globals and running scripts.

Additionally, as all `Air_` functions seem to tackle one specific part of the model, these should be moved to a separate Matlab package with a appropriate name.

<hr>

To do:
- [ ] Move all `Air_` files to their own package, with an appropriate name
- [ ] Convert `Air_sub` into a function. Use structures to reduce the amount of input and output variables.
- [ ] Add documentation to all functions
- [ ] Make the required changes in the main file.
- [ ] Create a pull request for the changes

### PR DESCRIPTION
**Pull request by SarahAlidoost**
### Description
closes #99
### Checklist
- [x] Add a reference to related issues.
- [x] @mentions of the person or team responsible for reviewing proposed changes.
- [x] This pull request has a descriptive title.
- [x] Code is written according to the [guidelines](http://cnl.sogang.ac.kr/cnlab/lectures/programming/matlab/Richard_Johnson-MatlabStyle2_book.pdf).
- [x] The checks by [MISS_HIT style checker and linter](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/CONTRIBUTING.md#follow-matlab-style-guidelines), below the pull request, are successful (green).
- [x] Documentation is available.
- [x] Add changes to the [changelog file](CHANGELOG.md) under section `Unreleased`.
- [x] Model runs successfully.
- [x] Ask a meinatainer to re-generate exe file if matlab codes are changed. About how to create an exe file, see [exe readme](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/run_model_on_snellius/exe/README.md).

This PR generates the same results as the main branch. Note that `dryair.solveDryAirEquations` runs only if `Soilairefc == 1`. However, the current value of `Soilairefc` is `0`, see [getModelSettings.m](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/%2Bio/getModelSettings.m). Therefore, this part of the code hasn't been tested before, see #196. I fixed the bugs and now when `Soilairefc==1` model runs and the refactored parts generate the same results as the old codes.

### CODE REVIEW

File: src/STEMMUS_SCOPE.m [hunk 1]
```diff
@@ -451,6 +431,7 @@
 
 % Srt, root water uptake;
 Srt = InitialValues.Srt;  % will be updated!
+P_gg = InitialValues.P_gg;  % will be updated!
```
Comment (BSchilperoort) [inline src/STEMMUS_SCOPE.m:434]: Nice that you figured this out! :+1:

**Review by BSchilperoort — COMMENTED** [review]
Looks very good! No comments from me :smile: 

Did you run the branch-comparison notebook already for these changes? Or should I do that.

**Comment by SarahAlidoost** [comment]
> Looks very good! No comments from me 😄
> 
> Did you run the branch-comparison notebook already for these changes? Or should I do that.

Thanks, yes I did it.
