### PR TITLE
Fix issue 96

### LINKED ISSUE #96: Refactor `SOIL1` and `SOIL2`
In the main `STEMMUS_SCOPE.m` script, on the following line `SOIL1` is run:
https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/d2fe0a671ab26430f086e1c8ee8272f4db6fa060/src/STEMMUS_SCOPE.m#L639

This is a relatively small script, which can probably be easily turned into a function. Also, the function description states that "This subroutine is called after one time step to update the wetting history". Wouldn't it make more sense to name this function `update_wetting_history`?

To refactor this function, the following has to be done:

- [ ] Determine the inputs and outputs of the function
- [ ] Rewrite it so it takes arguments as inputs, and returns the changed variables as output
- [ ] Change the main script to be compatible with these changes
- [ ] Commit the changes to a new branch and create a pull request

### PR DESCRIPTION
**Pull request by SarahAlidoost**
### Description
closes #96

### Update executable file
Please re-generate exe file if matlab codes are changed. About how to create an exe file, see [exe readme](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/run_model_on_snellius/exe/README.md).

### Checklist
- [x] Add a reference to related issues.
- [x] @mentions of the person or team responsible for reviewing proposed changes.
- [x] This pull request has a descriptive title.
- [x] Code is written according to the [guidelines](http://cnl.sogang.ac.kr/cnlab/lectures/programming/matlab/Richard_Johnson-MatlabStyle2_book.pdf).
- [x] The checks by [MISS_HIT style checker and linter](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/CONTRIBUTING.md#follow-matlab-style-guidelines), below the pull request, are successful (green).
- [x] Documentation is available.
- [x] Model runs successfully.

### CODE REVIEW

File: src/+init/defineSoilVariables.m [hunk 1]
```diff
@@ -0,0 +1,33 @@
+function SoilVariables = defineSoilVariables(InitialValues, SoilProperties, VanGenuchten)
+
```
Comment (BSchilperoort) [inline src/+init/defineSoilVariables.m:2]: A docstring at the start of the function definition would be nice.

File: src/+init/updateGamaH.m [hunk 2]
```diff
@@ -1,7 +1,11 @@
-function [Gama_h, Gama_hh] = updateGamaH(i, SoilConstants, SoilVariables)
+function [Gama_h, Gama_hh] = updateGamaH(i, SoilVariables)
+
+    % get soil constants
+    SoilConstants = io.getSoilConstants();
 
     hd = SoilConstants.hd;
     hm = SoilConstants.hm;
+
```
Comment (BSchilperoort) [inline src/+init/updateGamaH.m:8]:
```suggestion
```

File: src/CondL_h.m [hunk 3]
```diff
@@ -1,10 +1,13 @@
-function [Theta_LL, Se, KfL_h, KfL_T, DTheta_LLh, hh, hh_frez, Theta_UU, DTheta_UUh, Theta_II, KL_h] = CondL_h(SoilConstants, SoilVariables, Theta_r, Theta_s, Alpha, hh, hh_frez, h_frez, n, m, Ks, NL, Theta_L, h, KIT, TT, Thmrlefc, POR, SWCC, Theta_U, XCAP, Phi_s, RHOI, RHOL, Lamda, Imped, L_f, g, T0, TT_CRIT, Theta_II, KfL_h, KfL_T, KL_h, Theta_UU, Theta_LL, DTheta_LLh, DTheta_UUh, Se)
+function [Theta_LL, Se, KfL_h, KfL_T, DTheta_LLh, hh, hh_frez, Theta_UU, DTheta_UUh, Theta_II, KL_h] = CondL_h(SoilVariables, Theta_r, Theta_s, Alpha, hh, hh_frez, h_frez, n, m, Ks, NL, Theta_L, h, KIT, TT, Thmrlefc, POR, SWCC, Theta_U, XCAP, Phi_s, RHOI, RHOL, Lamda, Imped, L_f, g, T0, TT_CRIT, Theta_II, KfL_h, KfL_T, KL_h, Theta_UU, Theta_LL, DTheta_LLh, DTheta_UUh, Se)
```
Comment (BSchilperoort) [inline src/CondL_h.m:1]: Can't you use `SoilVariables` for more of the function I/O here? Like `Theta_LL`, `Theta_II`, etc. You made this change in `SOIL2.m`.

File: src/SOIL2.m [hunk 4]
```diff
@@ -1,7 +1,64 @@
...
+    hThmrl = ModelSettings.hThmrl;
+    Hystrs = ModelSettings.Hystrs;
+
+    Theta_s = VanGenuchten.Theta_s;
+    Theta_r = VanGenuchten.Theta_r;
+    Alpha = VanGenuchten.Alpha;
+    n = VanGenuchten.n;
+    m = VanGenuchten.m;
+
+    POR = SoilVariables.POR;
```
Comment (BSchilperoort) [inline src/SOIL2.m:22]: Instead of unpacking the struct, and then updating it. How about copying it with an alias (e.g. `SV` or `SVar`)? This would simplify this file a bit. I do agree that
```matlab
SoilVariables.Theta_V(i, ND) = SoilVariables.POR(i) - SoilVariables.Theta_UU(i, ND);
```
is a bit much. But this seems OK to me:
```matlab
SV.Theta_V(i, ND) = SV.POR(i) - SV.Theta_UU(i, ND);
```

**Review by BSchilperoort — APPROVED** [review]
Nice work Sarah! Just some small comments from me.

I assume you ran the model comparison notebook to verify that the results have not changed? I did not run the code.

File: src/CondL_h.m (hunk 3 above)
Comment (SarahAlidoost) [reply src/CondL_h.m:1]: Yes, I can, The function CondL_h will be refactored in #181.

File: src/SOIL2.m (hunk 4 above)
Comment (SarahAlidoost) [reply src/SOIL2.m:22]: agreed. But the problem is that some of the variables are still used as global in other scripts. Then, I need to unpack the structure. When all globals are removed. this refactoring can be applied.

Comment (BSchilperoort) [reply src/SOIL2.m]: But this happens in a function, and it has no global declarations, so that shouldn't be required.
