### PR TITLE
Fix issue 97

### LINKED ISSUE #97: Refactor `Forcing_PARM`
In STEMMUS_SCOPE.m, the script `Forcing_PARM` is called on the following line:.

https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/d2fe0a671ab26430f086e1c8ee8272f4db6fa060/src/STEMMUS_SCOPE.m#L713

I am not sure what this script does, as documentation is completely absent. It seems that it updates the input variables for the current timestep, using the forcing data loaded in previously.

As we need to remove all use of globals and scripts for both maintainability, readability and to be able to save & load the model state, this script has to be changed into a function.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
### Description
closes #97

Some part is fixed in https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/pull/88

### Update executable file
Please re-generate exe file if matlab codes are changed. About how to create an exe file, see [exe readme](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/run_model_on_snellius/exe/README.md).

### Checklist
- [x] Add a reference to related issues.
- [x] @mentions of the person or team responsible for reviewing proposed changes.
- [x] This pull request has a descriptive title.
- [x] Code is written according to the [guidelines](http://cnl.sogang.ac.kr/cnlab/lectures/programming/matlab/Richard_Johnson-MatlabStyle2_book.pdf).
- [x] The checks by [MISS_HIT style checker and linter](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/CONTRIBUTING.md#follow-matlab-style-guidelines), below the pull request, are successful (green).
- [x] Documentation is available.
- [x] Model runs successfully.

### CODE REVIEW

File: src/STEMMUS_SCOPE.m [hunk 1]
```diff
@@ -815,7 +797,38 @@
             hSAVE = hN;
         end
     end
-    run Forcing_PARM;
+    %% Reconstruct the driving forces to be a continuous function of time
+    if TIMEOLD == KT
```
Comment (BSchilperoort) [inline src/STEMMUS_SCOPE.m:801]: ~~So `KT` is the number of time steps, which is 0 in ModelSettings (??).~~
In `io.ModelSettings`, `KT` is set to 0, and is described as "the number of time steps". I think this is misleading, as it is not a setting. It is the counter for the _current_ time step.

Also, `TIMEOLD` is always 0:
`TIMEOLD = 0;` (line 546).

<hr>

Anyway, the code here sets all the values of these parameters to 0 for the first time step, but then right after it it sets them to a certain value? :confused: 

So for just one variable, as example:
```matlab
if KT == 0
    Ta(KT) = 0;
end

Ta(KT) = ForcingData.Ta_msr(KT)
```

What is the point of the `if KT == 0; varname(KT)  = 0; end` statement?

File: src/STEMMUS_SCOPE.m [hunk 2]
```diff
@@ -815,7 +797,38 @@
             hSAVE = hN;
         end
     end
-    run Forcing_PARM;
+    %% Reconstruct the driving forces to be a continuous function of time
```
[the remark this answers is not in the document]
Comment (BSchilperoort) [reply src/STEMMUS_SCOPE.m:800]: I saw that earlier it had the following comment
```
       Reconstruct the driving forces e.g. Ta, RH, Wind, Pressure,
        precipitation, etc. to be a continuous function of time via Fourier
        transformation, e.g. through identifying the dominant frequency etc.
```
Which makes me feel like this is part of never-finished code, which might as well be fully removed.

File: src/STEMMUS_SCOPE.m [hunk 3]
```diff
@@ -815,7 +797,38 @@
...
+    ForcingData.WS_msr(ForcingData.WS_msr < 0.05) = 0.05;
+    Ta(KT) = ForcingData.Ta_msr(KT);
+    HR_a(KT) = 0.01 .* (ForcingData.RH_msr(KT));
+    U(KT) = 100 .* (ForcingData.WS_msr(KT));
+    Rns(KT) = (ForcingData.Rns_msr(KT)) * 8.64 / 24 / 100 * 1;
+    TopPg(KT) = 100 .* (ForcingData.Pg_msr(KT));
+    Ts(KT) = Tss;
+    Rn(KT) = (ForcingData.Rn_msr(KT)) * 8.64 / 24 / 100 * 1;
+    Precip(KT) = ForcingData.Precip_msr(KT) * 0.1 / DELT;
+    Gvc(KT) = ForcingData.LAI_msr(KT);
```
Comment (BSchilperoort) [inline src/STEMMUS_SCOPE.m:826]: Shouldn't these steps happen during initialization? And without the `(KT)` indexing?

**Review by BSchilperoort — CHANGES_REQUESTED** [review]
Hi Sarah, I am quite confused as to what's going on in this code and why.

Could you clear this up, possible with the help of @yijianzeng and @Yunfei-Wang1993 ?

File: src/STEMMUS_SCOPE.m (hunk 2 above)
[the remark this answers is not in the document]
Comment (yijianzeng) [reply src/STEMMUS_SCOPE.m:800]: > I saw that earlier it had the following comment
> 
> ```
>        Reconstruct the driving forces e.g. Ta, RH, Wind, Pressure,
>         precipitation, etc. to be a continuous function of time via Fourier
>         transformation, e.g. through identifying the dominant frequency etc.
> ```
> 
> Which makes me feel like this is part of never-finished code, which might as well be fully removed.

Hi @BSchilperoort. The Fourier transformation was used to transfer the 'discrete' (e.g., half-houly or hourly) meto forcing to a continuous one (e.g., at second interval). This is done as such, because original STEMMUS model use the adaptive time intervals (from 1s to 1800s). This adaptive time interval is needed for making the model converge during precipitation events. 

During a rainfall event, soil moisture will change dramatically, then the numerical solution will not converge. However, if we reduce the time step (for the numerical solution) from 1800s to 900s, and in case not yet converged, reduced it further to 450s, and so on (till 1s as the shortest time step for the numerical solution). 

As such, we need to have the corresponding meto-forcing data for the above corresponding time steps (i.e. 900s, 450s etc.).

One can argue that we can just use the same meto-forcing, even the time-step is reduced. In that sense, we can indeed delete this part. Since, currently, we are not using the adaptive time steps in STEMMUS-SCOPE.

[the remark this answers is not in the document]
Comment (SarahAlidoost) [reply src/STEMMUS_SCOPE.m:800]: > Since, currently, we are not using the adaptive time steps in STEMMUS-SCOPE.

Do you mean that `Forcing_PARM.m` implements the "adaptive time steps" and currently the `Forcing_PARM.m` is not used in the main script `STEMMUS_SCOPE.m`? note that the main script runs `Forcing_PARM.m` at line [818](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/51668dcbc747ecc02f34473476a80412baa08bdd/src/STEMMUS_SCOPE.m#L818). I found that variables like `Rns` and `Rn` are calculated in `Forcing_PARM.m` script but never been used by other scripts. But `Forcing_PARM.m` also includes calculations like `HR_a(KT) = 0.01 .* (RH_msr(KT));` and `HR_a` is used in `Eval_Cal.m` script. Or `TopPg(KT) = 100 .* (Pg_msr(KT));` and  `TopPg` is used in `Air_BS.m`. Can you please explain these codes? are these related to "the adaptive time steps" and should be removed or these are only unit conversions and should be kept?

[the remark this answers is not in the document]
Comment (yijianzeng) [reply src/STEMMUS_SCOPE.m:800]: Hi Sarah, i am sorry for causing confusion. When i responded to Bart, i referred to earlier comment cited as "Reconstruct the driving forces e.g. Ta, ...". What i meant 'we can indeed remove this part', is only referring to the part linked to Fourier transformation.

And the Fourier transformation part has been removed.

[the remark this answers is not in the document]
Comment (yijianzeng) [reply src/STEMMUS_SCOPE.m:800]: > note that the main script runs `Forcing_PARM.m` at line [818](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/51668dcbc747ecc02f34473476a80412baa08bdd/src/STEMMUS_SCOPE.m#L818). I found that variables like `Rns` and `Rn` are calculated in `Forcing_PARM.m` script and used by other scripts. But `Forcing_PARM.m` also includes calculations like `HR_a(KT) = 0.01 .* (RH_msr(KT));` and `HR_a` is used in `Eval_Cal.m` script. Or `TopPg(KT) = 100 .* (Pg_msr(KT));` and `TopPg` is used in `Air_BS.m`. Can you please explain these codes? are these related to "the adaptive time steps" and should be removed or should be kept?

Yes, Sarah, these are needed in each time step to get the driving force to drive the STEMMUS-SCOPE. Those lines in 'Forcing_PARM' are used to convert unit to Centimeter-Gram-Second system.

They are not related to 'adaptive time steps'.

File: src/STEMMUS_SCOPE.m [hunk 4]
```diff
@@ -815,7 +797,38 @@
             hSAVE = hN;
         end
     end
-    run Forcing_PARM;
```
[the remark this answers is not in the document]
Comment (yijianzeng) [reply src/STEMMUS_SCOPE.m:818]: Hi Bart, see my response to Sarah above. This is used to get forcing data at each time step to drive STEMMUS-SCOPE.

File: src/STEMMUS_SCOPE.m (hunk 1 above)
Comment (yijianzeng) [reply src/STEMMUS_SCOPE.m:801]: > What is the point of the `if KT == 0; varname(KT) = 0; end` statement?

Hi, Bart, this is for the initialization of the model before the time step starts.

File: src/STEMMUS_SCOPE.m (hunk 3 above)
Comment (yijianzeng) [reply src/STEMMUS_SCOPE.m:826]: > 

Hi Bart, (KT) is needed. for each time step, forcing data at that particular time step (KT) should be used to drive the model.

File: src/STEMMUS_SCOPE.m (hunk 4 above)
[the remark this answers is not in the document]
Comment (SarahAlidoost) [reply src/STEMMUS_SCOPE.m:818]: only a few lines of Forcing_PARM are actually used in the model, the rest are unused.

File: src/STEMMUS_SCOPE.m (hunk 1 above)
Comment (SarahAlidoost) [reply src/STEMMUS_SCOPE.m]: all the if stetmanets in `Forcing_PARM` are unused. Also, the `if TIMEOLD == KT` does not happen.

File: src/STEMMUS_SCOPE.m (hunk 3 above)
Comment (SarahAlidoost) [reply src/STEMMUS_SCOPE.m]: some lines are fixing e.g. `ForcingData.WS_msr(ForcingData.WS_msr < 0.05) = 0.05;`, some are unit conversion e.g. `TopPg(KT) = 100 .* (ForcingData.Pg_msr(KT));`, some are variable definition e.g. `Ts(KT) = Tss;`, and some are adaptive time step e.g.  `Rn(KT) = (ForcingData.Rn_msr(KT)) * 8.64 / 24 / 100 * 1;` that are not used in the model.

Comment (yijianzeng) [reply src/STEMMUS_SCOPE.m]: > and some are adaptive time step e.g. `Rn(KT) = (ForcingData.Rn_msr(KT)) * 8.64 / 24 / 100 * 1;`

Hi Sarah, this is also unit conversion, not an adaptive time step.

File: src/STEMMUS_SCOPE.m [hunk 5]
```diff
@@ -568,7 +550,13 @@
...
 
-% Cause the start of simulation period is from 0mins, while the input data start from 30mins.
+% Convert unit to Centimeter-Gram-Second system
+% see issue 188 to refactor these lines
+HR_a = 0.01 .* (ForcingData.RH_msr);
+U = 100 .* (ForcingData.WS_msr);
+TopPg = 100 .* (ForcingData.Pg_msr);
+
+% the start of simulation period is from 0mins, while the input data start from 30mins.
 tS = DURTN / Delt_t;
```
Comment (BSchilperoort) [inline src/STEMMUS_SCOPE.m:560]:
```matlab
tS = DURTN / Delt_t;
```
It seems that `tS` is a synonym for `Dur_tot`...

see:
```matlab
DURTN = TimeProperties.DELT * TimeProperties.Dur_tot; % Duration of simulation period;
Delt_t = TimeProperties.DELT; % Duration of time step [Unit of second]
```

And then the following line can also be refactored:
```
TEND = TIME + DURTN; % Time to be reached at the end of simulation period
```
to

```matlab
TEND = TIME + TimeProperties.DELT * TimeProperties.Dur_tot;
```

(TEND is not a global, and tS isn't either).

So I think this is a good chance to get rid of two more excess variables (DURTN, tS) :sweat_smile:

File: src/STEMMUS_SCOPE.m [hunk 6]
```diff
@@ -815,7 +803,11 @@
             hSAVE = hN;
         end
     end
-    run Forcing_PARM;
+
```
Comment (BSchilperoort) [inline src/STEMMUS_SCOPE.m:806]: Perhaps a short comment here explaining why the variables are (re)set here could be useful.

**Review by BSchilperoort — APPROVED** [review]
Great! It's good to see there are now fewer lines and fewer variables.
Just two small comments from me.

File: src/STEMMUS_SCOPE.m (hunk 5 above)
Comment (SarahAlidoost) [reply src/STEMMUS_SCOPE.m]: Done!

File: src/STEMMUS_SCOPE.m (hunk 6 above)
Comment (SarahAlidoost) [reply src/STEMMUS_SCOPE.m:803]: Done!
